// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	syncPlatforms: (platforms: PlatformType[], sigaa: {
	matricula: string,
	senha: string,
} | null, aprender3: {
	cpf: string,
	senha: string,
} | null, teams: {
	isConnected: boolean | null,
	email: string | null,
} | null) => typedError<SyncResult, string>(__TAURI_INVOKE("sync_platforms", { platforms, sigaa, aprender3, teams })),
	checkVaultStatus: () => __TAURI_INVOKE<VaultStatus>("check_vault_status"),
	getSigaaDepartments: () => typedError<Department[], string>(__TAURI_INVOKE("get_sigaa_departments")),
	scrapeSigaaClasses: (departmentId: string, year: string, period: string) => typedError<ScrapedDiscipline[], string>(__TAURI_INVOKE("scrape_sigaa_classes", { departmentId, year, period })),
	getCoursesCatalog: () => typedError<CourseCatalogItem[], string>(__TAURI_INVOKE("get_courses_catalog")),
	getCourseCurriculum: (courseId: string) => typedError<CurriculumStructure[], string>(__TAURI_INVOKE("get_course_curriculum", { courseId })),
	solveSchedules: (candidateClasses: ScrapedClass[], preferenceShift: string | null) => typedError<ScheduleOption[], string>(__TAURI_INVOKE("solve_schedules", { candidateClasses, preferenceShift })),
	checkScheduleConflicts: (classes: ScrapedClass[]) => typedError<string[], string>(__TAURI_INVOKE("check_schedule_conflicts", { classes })),
	openExternalUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_external_url", { url })),
};

/* Types */
export type Aprender3Creds = {
	cpf: string,
	senha: string,
};

export type Course = {
	id: string,
	code: string,
	name: string,
	semester: string,
	platform: PlatformType,
	professor: string | null,
	classroom: string | null,
	schedule: string | null,
	unreadCount: number | null,
	pendingAssignmentsCount: number | null,
	url: string | null,
};

export type CourseCatalogItem = {
	id: string,
	name: string,
	degree: string,
	shift: string,
	campus: string,
	modality: string,
	coordinator?: string | null,
	curricula_ids?: string[],
};

export type CurriculumDiscipline = {
	code: string,
	name: string,
	workload_hours: number,
	level?: number | null,
	nature: string,
	prerequisites_raw?: string | null,
	prerequisites?: string[],
	equivalences_raw?: string | null,
	equivalences?: string[],
};

export type CurriculumStructure = {
	id: string,
	course_id: string,
	course_name: string,
	code: string,
	created_year?: string | null,
	status: string,
	shift?: string | null,
	total_hours?: number | null,
	mandatory_disciplines?: CurriculumDiscipline[],
	elective_disciplines?: CurriculumDiscipline[],
	complementary_disciplines?: CurriculumDiscipline[],
};

export type Department = {
	id: string,
	name: string,
};

export type FeedItem = {
	id: string,
	platform: PlatformType,
	title: string,
	content: string,
	courseName: string,
	courseCode: string | null,
	author: string | null,
	itemType: FeedItemType,
	createdAt: string,
	dueDate: string | null,
	isCompleted: boolean | null,
	externalUrl: string | null,
};

export type FeedItemType = "post" | "assignment";

export type PlatformType = "sigaa" | "aprender3" | "teams";

export type ScheduleOption = {
	id: string,
	classes: ScrapedClass[],
	has_conflict: boolean,
	conflicts: string[],
	score: number,
};

export type ScheduleSlot = {
	day: number,
	day_name: string,
	shift: string,
	period: number,
	time_range: string,
	global_slot_index: number,
};

export type ScrapedClass = {
	id: string,
	discipline_code: string,
	discipline_name: string,
	class_code: string,
	teachers?: string[],
	classroom?: string,
	schedule_code: string,
	schedule_description?: string | null,
	date_range?: string | null,
	schedule_slots?: ScheduleSlot[],
	vacancies?: number | null,
	occupied?: number | null,
};

export type ScrapedDiscipline = {
	code: string,
	name: string,
	department_id: string,
	classes: ScrapedClass[],
};

export type SigaaCreds = {
	matricula: string,
	senha: string,
};

export type SyncResult = {
	items: FeedItem[],
	courses: Course[],
	syncedAt: string,
	errors: Partial<{ [key in PlatformType]: string }> | null,
};

export type TeamsCreds = {
	isConnected: boolean | null,
	email: string | null,
};

export type VaultStatus = {
	status: string,
	encryption: string,
	zeroTelemetry: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

